### ISSUE TITLE
pre_processing.py about bci_iv_2a

### ISSUE THREAD

**Issue by 1MrDark** [DuanYiqun/CTNAS-EEG#1]
![image](https://user-images.githubusercontent.com/86149154/227781254-6ffb5641-d585-4158-8d8e-b8eaefd3d0b5.png)
Hello, I want to know how the data here is obtained. It looks not the original data.
thank you very much.

**Comment by duanyiqun** [comment]
Hi there, 
I just filtered the data from each subject only. For example, ```A0_1_T.mat``` only contains the data from subject 1 for the bci_iv_2a dataset. For the format, just keeping it the same as EEGNet will work.
